package tests;

import org.testng.Assert;
import org.testng.annotations.*;
import pages.LoginPage;
import utilities.DriverFactory;
import org.openqa.selenium.WebDriver;
import utilities.ExcelReaderUtil;

@Listeners(listeners.TestListener.class)
public class LoginTests {

    WebDriver driver;
    LoginPage loginPage;

    private static final String XLSX_PATH = System.getProperty("user.dir") + "/test-data/generatedUsers.xlsx";

    @BeforeMethod
    public void setup() {
        driver = DriverFactory.getDriver();
        driver.get("https://petstore.octoperf.com/actions/Account.action?signonForm=");
        loginPage = new LoginPage(driver);
    }
    @DataProvider(name = "excelUsers")
    public Object[][] excelUsers() {
        return ExcelReaderUtil.getExcelData(System.getProperty("user.dir") + "/test-data/generatedUsers.xlsx", "Users");
    }

    @Test(dataProvider = "excelUsers")
    public void loginWithExcelData(String username, String password, String firstName, String lastName, String email,
                                   String phone, String address1,String address2, String city, String state, String zip, String country) {

        // Use only username & password for login
        loginPage.enterUsername(username);
        loginPage.enterPassword(password);
        loginPage.clickLogin();

        // If login is valid, page title or welcome text should indicate success; otherwise error visible.
        // We do a basic check: if error visible -> failure expected, otherwise success assumed
        boolean error = loginPage.isErrorVisible();

        // If the CSV was generated by our registration test, username/password pair should be valid
        // so we assert NOT error.
        Assert.assertFalse(error, "Login failed for user: " + username);
    }

    @AfterMethod
    public void teardown() {
        DriverFactory.quitDriver();
    }
}
